name: Make TWRP source snapshot
on:
  workflow_dispatch: {}

env:
  MANIFEST_URL: https://github.com/Harlock1978/TWRP-Ulefone-Armor28-Ultra-NEEA.git
  MANIFEST_BRANCH: twrp-14.1

jobs:
  snapshot:
    runs-on: ubuntu-22.04
    steps:
      - name: Free disk space (optional)
        run: |
          sudo rm -rf /usr/local/lib/android || true
          df -h

      - name: Install deps + repo tool
        run: |
          sudo apt-get update
          sudo apt-get install -y git-core curl python3 lz4
          mkdir -p $HOME/bin
          curl -o $HOME/bin/repo https://storage.googleapis.com/git-repo-downloads/repo
          chmod a+x $HOME/bin/repo
          echo "$HOME/bin" >> $GITHUB_PATH

      # Se in futuro il repo torna privato o qualche <project> è privato,
      # sblocca l'autenticazione aggiungendo un PAT come secret GH_PAT
      # e decommenta questo step:
      - name: Configure Git auth for GitHub
        env:
         GH_ACTOR: ${{ github.actor }}
         GH_TOKEN: ${{ github.token }}
        run: |
          git config --global url."https://${GH_ACTOR}:${GH_TOKEN}@github.com/".insteadOf "https://github.com/"
          git config --global url."https://${GH_ACTOR}:${GH_TOKEN}@github.com/".insteadOf "git@github.com:"
          git config --global url."https://${GH_ACTOR}:${GH_TOKEN}@github.com/".insteadOf "ssh://git@github.com/"


      - name: repo init + sync (your manifest fork)
        run: |
          mkdir -p ~/twrp && cd ~/twrp
          repo init --depth=1 -u "$MANIFEST_URL" -b "$MANIFEST_BRANCH"
          repo sync -c -j8

      - name: Shrink snapshot (drop VCS metadata)
        run: |
          cd ~/twrp
          rm -rf .repo
          find . -name ".git" -type d -prune -exec rm -rf {} +
          tar -czf /tmp/twrp-src-snapshot.tar.gz .

      - name: Split into 1.9GB chunks (artifact per-part limit)
        run: |
          cd /tmp
          split -b 1900m twrp-src-snapshot.tar.gz twrp-src-snapshot.tar.gz.part-

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: twrp-src-snapshot
          path: /tmp/twrp-src-snapshot.tar.gz.part-*
